### DISCUSSION TITLE
Automatically building a GitHub Pages site

### DISCUSSION THREAD

**Discussion by qtzar** [avisi-cloud/structurizr-site-generatr#178] [Show and tell]
Not an issue but wasn't sure where to put this but I have been able to build out a GitHub Action to create the static site in a gh-pages branch which you can then publish using GitHub Pages.

Create a file like buildsite.yml in the .github/workflows directory in your repository with the following contents. Make sure you have a file called workspace.dsl in the root of the repository or change the location in the docker run command line as required.

Hope this helps somebody.

----

```
name: Publish C4 Model
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          persist-credentials: false
          fetch-depth: 0
        
      - name: Build Site
        run: docker run --user root -t --rm -v ${{ github.workspace }}:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr generate-site -w workspace.dsl
        shell: bash
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/site
```

**Comment by dirkgroot** [comment]
Thanks! I've converted your issue to a discussion in the Q&A section.

**Comment by qtzar** [comment]
If you want to build multiple branches using a GitHub workflow you can use the following yaml.

Just replace the Repository URL and the branch names with the values that you need.

```
name: Publish C4 Model

on:
  push:
    branches:
      - '**'                  # matches every branch
      - '!gh-pages'    # excludes the GitHub Pages deployment branch
      
jobs:
  build-and-publish:
    runs-on: [ self-hosted, azure ]
    steps:
    - name: Build Site
        run: docker run --user root -t --rm -v ${{ github.workspace }}:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr generate-site  -g https://github.com/<REPOSITORTYURL>git -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} -w workspace.dsl -b master,<BRANCH2>,<BRANCH3> -d master -a assets
        shell: bash
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          FOLDER: build/site
```
